field_visibility_rules:
  type: objects
  default: |
    - field_name: company
      allowed_group: netwrix_employees
  description: "List of field visibility rules. Each rule defines which group can see which custom user field."
  schema:
    name: field_visibility_rule
    properties:
      field_name:
        type: string
        required: true
        description: "The name of the custom user field (e.g., 'company', 'department', 'location')"
      allowed_group:
        type: string
        required: true
        description: "The name of the group that can see this field"
